name: dbt_

profile: dbt

model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
    +persist_docs:
      relation: true
      columns: true
    dbt:
      +static_analysis: strict
