x-airflow-common-dev: &airflow-common-dev
  build:
    context: ../..
    dockerfile: infra/airflow/Dockerfile
    target: ${ENV:-dev}

x-airflow-volumes: &airflow-volumes
  volumes:
    - ${AIRFLOW_PROJ_DIR:-../..}/airflow/tests:/opt/airflow/tests
    - ${AIRFLOW_PROJ_DIR:-../..}/pytest.ini:/opt/airflow/pytest.ini

services:
  airflow-apiserver:
    <<: [*airflow-common-dev, *airflow-volumes]

  airflow-scheduler:
    <<: *airflow-common-dev

  airflow-dag-processor:
    <<: *airflow-common-dev

  airflow-worker:
    <<: *airflow-common-dev

  airflow-triggerer:
    <<: *airflow-common-dev

  airflow-init:
    <<: *airflow-common-dev

  airflow-cli:
    <<: [*airflow-common-dev, *airflow-volumes]

  flower:
    <<: *airflow-common-dev
